server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/demo
    username: demo
    password: secret
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.example.employee: DEBUG
