server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: http://employee-service:8081
          predicates:
            - Path=/employees
            - Path=/employees/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
